version: '3.7'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: wiremind_owner
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: wiremind
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
